# -*- conf -*-

font=caskaydiaCoveNF:size=14

[cursor]
style=beam
# color=000000 FED7D9
color=191724 e0def4 
beam-thickness=2

# gruvbox
# [colors]
# alpha=1.0
# foreground=ebdbb2
# background=1d2021
# regular0=282828 # black
# regular1=cc241d # red
# regular2=98971a # green
# regular3=d79921 # yellow
# regular4=458588 # blue
# regular5=b16286 # magenta
# regular6=689d6a # cyan
# regular7=a89984 # white
# bright0=928374 # bright black
# bright1=fb4934 # bright red
# bright2=b8bb26 # bright green
# bright3=fabd2f # bright yellow
# bright4=83a598 # bright blue
# bright5=d3869b # bright magenta
# bright6=8ec07c # bright cyan
# bright7=ebdbb2 # bright white

# rose-pine
[colors]
background=191724 
# foreground=e0def4 
foreground=ebdbb2

regular0=26233a     # black (Overlay)
regular1=eb6f92     # red (Love)
regular2=9ccfd8     # green (Foam)
regular3=f6c177     # yellow (Gold)
regular4=31748f     # blue (Pine)
regular5=c4a7e7     # magenta (Iris)
regular6=ebbcba     # cyan (Rose)
regular7=e0def4     # white (Text)

bright0=47435d      # bright black (lighter Overlay)
bright1=ff98ba      # bright red (lighter Love)
bright2=c5f9ff      # bright green (lighter Foam)
bright3=ffeb9e      # bright yellow (lighter Gold)
bright4=5b9ab7      # bright blue (lighter Pine)
bright5=eed0ff      # bright magenta (lighter Iris)
bright6=ffe5e3      # bright cyan (lighter Rose)
bright7=fefcff      # bright white (lighter Text)

flash=f6c177        # yellow (Gold)
